import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useMoralisWeb3Api } from "react-moralis";
import InputForm from "../pageComponents/InputForm";
import TxTable from "../pageComponents/TxTable";
import Signup from "../pageComponents/Signup";

export default function Home() {
    const [displayData, setDisplayData] = useState([]);
    const [account, setAccount] = useState(
        "0x48b7cedF1D50cE6595a027c9234D5e5Bef54E09C"
    );
    const Web3Api = useMoralisWeb3Api();

    async function getTransactions(chain) {
        const options = { chain: chain, address: account };
        const data = await Web3Api.account.getTransactions(options);
        setDisplayData(data.result);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Watch Wallet Address</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <Signup /> */}

            <main className={styles.main}>
                <h1 className={styles.title}>Watch Wallet Address</h1>

                <p className={styles.description}>
                    Enter a wallet address and choose required parameters
                </p>

                <InputForm
                    getTransactions={getTransactions}
                    setAccount={setAccount}
                />

                <TxTable displayData={displayData} />
            </main>
        </div>
    );
}
